In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('bert_data.csv')

In [4]:
train_args = {
    'reprocess_input_data': True,
    'overwrite_output_dir': True,
    'evaluate_during_training': False,
    'max_seq_length': 512,
    'num_train_epochs': 2,
    'evaluate_during_training_steps': 50,
    #'wandb_project': 'sts-b-medium',
    'train_batch_size': 16,
    'regression': False,
}

In [5]:
from simpletransformers.classification import ClassificationModel
model = ClassificationModel('bert', 'bert-base-uncased', num_labels=3, args=train_args, use_cuda = False)

In [6]:
from sklearn.metrics import f1_score, accuracy_score

In [47]:
from sklearn.model_selection import train_test_split
train_df, eval_df = train_test_split(df[["text","labels"]], test_size=0.33, random_state=42)

In [ ]:
eval_df.text

In [15]:
model.train_model(train_df, f1=f1_score)

KeyboardInterrupt: 

In [49]:
eval_df = eval_df.reset_index().drop(["index"], axis = 1)

In [50]:
eval_df

text  labels
0                                                  Ads       2
1    - Customer Churn Forecasting Model: building t...       0
2                                     Network Engineer       1
3    •\tDrafted MoP for logical design of vEPC GW R...       1
4    ●\tDesign and deployment of an entirely new Da...       1
..                                                 ...     ...
288         Microsoft Dynamics AX Technical Consultant       2
289  •\tWorked on BIGIQ SSL Orchestrator, which hel...       2
290  SDE Intern at Directory Service team under AWS...       2
291  I mainly focus on Presto as a service for all ...       2
292  • Leading a team of 3 data scientists conducti...       0

[293 rows x 2 columns]

In [51]:
pred = model.predict(eval_df["text"])

KeyboardInterrupt: 

In [ ]:
pred

In [ ]:
import numpy as np
labels = np.array(eval_df["labels"])

In [35]:
from sklearn.metrics import confusion_matrix,classification_report

In [52]:
print(confusion_matrix(labels,pred[0]))

[[ 48   2  11]
 [  0  83   9]
 [ 14   5 121]]


In [55]:
print(classification_report(labels, pred[0]))

              precision    recall  f1-score   support

           0       0.77      0.79      0.78        61
           1       0.92      0.90      0.91        92
           2       0.86      0.86      0.86       140

    accuracy                           0.86       293
   macro avg       0.85      0.85      0.85       293
weighted avg       0.86      0.86      0.86       293



In [54]:
 model.predict(["use AWS for data preprocessing and visualiztion. Build machine learning pipeline"])

(array([2]), array([[ 0.74307406, -1.7775049 ,  1.1213375 ]], dtype=float32))

In [60]:
model = ClassificationModel('bert', 'outputs/', args=train_args, use_cuda = False)

In [61]:
model.predict([""])

(array([2]), array([[ 0.74307406, -1.7775049 ,  1.1213375 ]], dtype=float32))